version: "3.8"
services:
  headscale:
    image: headscale/headscale:0.23.0
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - /containers/headscale/config:/etc/headscale
      - /containers/headscale/data:/var/lib/headscale
    ports:
      - "8088:8088"
      - "50443:50443"
    networks:
      - headscale-net

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8089:8080"
    networks:
      - headscale-net

networks:
  headscale-net:
    driver: bridge