http:
 #region routers
  routers:
    #PORTAINER
    portainer:
      entryPoints:
        - "https"
      rule: "Host(`port.argaceve.com`)"
      middlewares:
        - default-headers
        - https-redirect
      tls:
        certResolver: "cloudflare"
      service: portainer
    #VAULTWARDEN
    vault-warden:
      entryPoints:
        - "https"
      rule: "Host(`passvault.argaceve.com`)"
      middlewares:
        - default-headers
        - https-redirect
      tls:
        certResolver: "cloudflare"
      service: vault-warden
    #HEADSCALE
    headscale:
      entryPoints:
        - "https"
      rule: "Host(`hs.argaceve.com`)"
      middlewares:
        - default-headers
        - https-redirect
        - headscale-cors
      tls:
        certResolver: "cloudflare"
      service: headscale
    #HEADSCALE UI
    headscale-ui:
      entryPoints:
        - "https"
      rule: "Host(`hsui.argaceve.com`)"
      middlewares:
        - default-headers
        - https-redirect
        - headscale-ui-auth
      tls:
        certResolver: "cloudflare"
      service: headscale-ui
    #UNIFI
    unifi:
      entryPoints:
        - "https"
      rule: "Host(`unifi.argaceve.com`)"
      middlewares:
        - default-headers
        - https-redirect
      tls:
        certResolver: "cloudflare"
      service: unifi
#endregion

#region services
  services:
    #PORTAINER
    portainer:
      loadBalancer:
        servers:
          - url: "https://23.95.205.205:9443"
        passHostHeader: true
    #VAULTWARDEN
    vault-warden:
      loadBalancer:
        servers:
          - url: "http://23.95.205.205:8082"
        passHostHeader: true
    #HEADSCALE
    headscale:
      loadBalancer:
        servers:
          - url: "http://23.95.205.205:8088"
        passHostHeader: true
    #HEADSCALE-UI
    headscale-ui:
      loadBalancer:
        servers:
          - url: "http://23.95.205.205:8089"
        passHostHeader: true
    #UNIFI
    unifi:
      loadBalancer:
        servers:
          - url: "https://23.95.205.205:8443"
        passHostHeader: true
#endregion

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    headscale-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
        accessControlAllowOriginList:
          - "https://hsui.argaceve.com"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100

    headscale-ui-auth:
      basicAuth:
        users:
          - "hsadmin:$2y$05$xCc8/l98mEwDiTBccZi/puVkUB/A.eG7rUYz.OOHFwBY3wrqqyrVi"
          